In [46]:
import pandas as pd
from imdb import Cinemagoer

# Genome Scores

In [2]:
genome_scores = pd.read_csv("Data/genome-scores.csv")
genome_scores.head()

   movieId  tagId  relevance
0        1      1    0.02900
1        1      2    0.02375
2        1      3    0.05425
3        1      4    0.06875
4        1      5    0.16000

In [3]:
print(genome_scores.shape)
print(len(genome_scores["movieId"].unique()))
print(len(genome_scores["tagId"].unique()))

(14862528, 3)
13176
1128

In [4]:
## Not all movies have the relevance scores, so we will see what can be done about it

In [5]:
genome_scores[genome_scores['relevance'].isna()]
## concluded no null values

Empty DataFrame
Columns: [movieId, tagId, relevance]
Index: []

# Genome Tags (tagId, tag)

In [4]:
genome_tags= pd.read_csv("Data/genome-tags.csv")
genome_tags.head()

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [61]:
print(genome_tags.shape)
print(len(genome_tags["tag"].unique()))
print(len(genome_tags["tagId"].unique()))
## Both tag and tagId are unique

(1128, 2)
1128
1128

# Links csv

In [20]:
links= pd.read_csv("Data/links.csv")
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [21]:
print(links.shape)
print(len(links["movieId"].unique()))
print(len(links["imdbId"].unique()))
print(len(links["tmdbId"].unique()))

(58098, 3)
58098
58098
57878

In [22]:
df1 = links.dropna()
print(df1.shape)
print(links.shape)

(57917, 3)
(58098, 3)

In [23]:
links.dtypes

movieId      int64
imdbId       int64
tmdbId     float64
dtype: object

In [24]:
#print(len(links.loc["movieId"==1]))
#links.loc[(links['tmdbId'] == "Null" )]
links[links['tmdbId'].isna()]

       movieId   imdbId  tmdbId
709        721   114103     NaN
718        730   125877     NaN
756        769   116992     NaN
757        770    38426     NaN
778        791   113610     NaN
...        ...      ...     ...
24855   114963   322250     NaN
25029   115715  3670792     NaN
25057   115821  3900116     NaN
29740   128734  4438688     NaN
37905   148093  4006044     NaN

[181 rows x 3 columns]

 #### Links csv is almost redundant

# Movies csv

In [6]:
movies= pd.read_csv("Data/movies.csv")
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [7]:
print(movies.shape)
print(len(movies["movieId"].unique()))
## So we have movieId unique

(58098, 3)
58098

In [69]:
genre_array=[]
count=0
no_genre_movies=[]
#no_genre_list

for x,m,i in zip(movies['genres'],movies['title'],movies['movieId']):
    gen=x.split('|')
    for y in gen:
        if y=='(no genres listed)':
            no_genre_movies.append([m,i])
            count+=1
        genre_array.append(y)
# genre_array.append(gen)
# print(x)
# words = string.split(',')
# print(words)

In [70]:
# pip install IMDbPY
# movies with no genre --(movie_title,movies_id)
# no_genre

In [74]:
print(set(genre_array))
print(count)
## movies with no genre --(movie_title,movies_id)
no_genre_movies

{'Children', 'War', 'Thriller', 'Musical', 'Animation', 'Mystery', '(no genres listed)', 'Comedy', 'Adventure', 'Western', 'Drama', 'Romance', 'Horror', 'Sci-Fi', 'Crime', 'Fantasy', 'Documentary', 'IMAX', 'Action', 'Film-Noir'}
4266

[['Away with Words (San tiao ren) (1999)', 83773],
 ['Scorpio Rising (1964)', 83829],
 ['Glitterbug (1994)', 84768],
 ['Age of the Earth, The (A Idade da Terra) (1980)', 86493],
 ['Trails (Veredas) (1978)', 87061],
 ['Milky Way (Tejút) (2007)', 91246],
 ['Dancing Hawk, The (Tanczacy jastrzab) (1978)', 92435],
 ['Warsaw Bridge (Pont de Varsòvia) (1990)', 92641],
 ['Ella Lola, a la Trilby (1898)', 94431],
 ['Turkish Dance, Ella Lola (1898)', 94657],
 ['Blacksmith Scene (1893)', 95541],
 ['Promise of the Flesh (Yukcheui yaksok) (1975)', 95750],
 ['Nocturno 29 (1968)', 96479],
 ['Les hautes solitudes (1974)', 96651],
 ['Direct from Brooklyn (1999)', 113472],
 ['Primus Hallucino-Genetics Live 2004 (2004)', 113545],
 ['La cravate (1957)', 114335],
 ["Glumov's Diary (Dnevnik Glumova) (1923)", 114587],
 ['At Land (1944)', 114723],
 ['Study in Choreography for Camera, A (1945)', 114725],
 ['Guernica (1950)', 114877],
 ["It's My Mother's Birthday Today (2008)", 115004],
 ['Spare Bed-Room (1969)', 115006],
 ['Maria (Mariya) (1989)', 115419],
 ["(Absolutions) Pipilotti's Mistakes ((Entlastungen) Pipilottis Fehler) (1988)",
  115441],
 ['Judgement Day (1983)', 115529],
 ['Two Solutions for One Problem (Dow Rahehal Baraye yek Massaleh) (1975)',
  115602],
 ['Madame Bovary (2000)', 115893],
 ['Christmas Oranges (2012)', 116046],
 ['Clockwork Mice (1995)', 116054],
 ['Lettera Amorosa (1995)', 116096],
 ['Passeio com Johnny Guitar (1996)', 116098],
 ['Conserva Acabada (1990)', 116100],
 ['Complicit (2013)', 116126],
 ['Conquest of Cochise (1953)', 116237],
 ['Crime and Punishment, USA (1959)', 116287],
 ['Danger Zone (1996)', 116347],
 ['Ecstasy in Entropy (1999)', 116425],
 ["Let's Spend the Night Together (1982)", 116479],
 ['Say It with Songs (1929)', 116531],
 ['Zanjeer (1973)', 116704],
 ['Whoregasm (1988)', 116917],
 ['Kiss Me Goodbye (1986)', 116923],
 ['Thrust in Me (1985)', 116949],
 ['The Wild World of Lydia Lunch (1983)', 116955],
 ['Fillmore (1972)', 117316],
 ['The Forgotten Faces (1961)', 117722],
 ['T,O,U,C,H,I,N,G (1969)', 117845],
 ['Little Hamlet (1960)', 117847],
 ['The Menacing Eye (1960)', 117865],
 ['Blow Job (1963)', 118292],
 ['In Order Not to Be Here (2002)', 118340],
 ['The Hearts of Age (1934)', 118448],
 ['A True Mob Story (1998)', 118692],
 ['Un centesimo di secondo (1981)', 118728],
 ['Sekirei (2008)', 118878],
 ["Solomon Northup's Odyssey (1984)", 119878],
 ['Eye for an Eye (1966)', 120299],
 ["If I'm Lucky (1946)", 120612],
 ['Blablablá (1975)', 121581],
 ['Confessor Caressor (1989)', 121590],
 ['Where Do We Go from Here? (1945)', 121867],
 ['Sally (1929)', 122001],
 ['Howling VI: The Freaks (1991)', 122482],
 ['American Black Beauty (2005)', 122557],
 ['The Wrong Woman (2013)', 122571],
 ['Expecting Amish (2014)', 122573],
 ['Night Song (1947)', 122589],
 ['Two Tickets to Broadway (1951)', 122605],
 ['The First Traveling Saleslady (1956)', 122637],
 ['Nana (1926)', 122675],
 ['John Goldfarb, Please Come Home! (1965)', 122679],
 ['Black Horizon (2002)', 122687],
 ['Oliver Twist (1999)', 122711],
 ['The Last Flight (1931)', 122811],
 ['Starlift (1951)', 122825],
 ['Ben-hur (2016)', 122888],
 ['Pirates of the Caribbean: Dead Men Tell No Tales (2017)', 122896],
 ['The Trans-Atlantic Mystery (1932)', 122944],
 ['Someone To Love (1988)', 122988],
 ['Hammersmith Is Out (1972)', 123010],
 ['The Racers (1955)', 123038],
 ['Stalingrad (1989)', 123044],
 ['No Greater Glory (1934)', 123052],
 ['Goodbye, Mr. President (1987)', 123061],
 ['Red Dust (1990)', 123071],
 ['Left for Dead (2007)', 123095],
 ['The American Success Company (1980)', 123117],
 ['Street Girl (1929)', 123135],
 ['The Divine Woman (1928)', 123139],
 ['The Great Man (1956)', 123250],
 ['State Fair (1962)', 123254],
 ['Katherine (1975)', 123274],
 ['Conspiracy: The Trial of the Chicago 8 (1987)', 123278],
 ['Crown Heights (2004)', 123290],
 ['Lucrèce Borgia (1935)', 123333],
 ['Tower of Nesle (1955)', 123339],
 ['Heatseeker (1995)', 123345],
 ['Struggle in the Valley (1954)', 123371],
 ['Lotte from Gadgetville (2006)', 123397],
 ['Poster Girl (2010)', 123415],
 ['Newlyweeds (2013)', 123421],
 ['Wuthering Heights (2003)', 123439],
 ['Certain Fury (1985)', 123441],
 ['Hell Below (1933)', 123518],
 ['While the City Sleeps (1928)', 123526],
 ['Spitfire (1995)', 123559],
 ["Maybe I'll Come Home in the Spring (1971)", 123602],
 ['The Night That Panicked America (1975)', 123607],
 ['Goldengirl (1979)', 123609],
 ['Memorial Day (1983)', 123617],
 ['Terrible Joe Moran', 123619],
 ['The Karen Carpenter Story (1989)', 123625],
 ['Caroline? (1990)', 123629],
 ['The Brigand of Kandahar (1965)', 123693],
 ['Looking For Love (1964)', 123709],
 ["The Munsters' Revenge (1981)", 123715],
 ['Love Is Better Than Ever (1952)', 123721],
 ['Lily Boy (1954)', 123729],
 ['Stranded (1935)', 123755],
 ['High Pressure (1932)', 123775],
 ['The Quest: The Longest Drive (1976)', 123798],
 ['Long Pants (1927)', 123800],
 ['The Conquering Power (1921)', 123808],
 ['The Great Sioux Massacre (1965)', 123810],
 ['Le port du désir (1955)', 123830],
 ['The Black Klansman (1966)', 123838],
 ['Astro-Zombies M3: Cloned (2010)', 123850],
 ['Red Skies of Montana (1952)', 123860],
 ["I'd Climb the Highest Mountain (1951)", 123866],
 ['Operation Delta Force 4: Deep Fault (1999)', 123870],
 ['Touched By Love (1980)', 123874],
 ['The Rosebud Beach Hotel (1984)', 123902],
 ['Gribouille (1937)', 123913],
 ["Lady Chatterley's Lover (1955)", 123925],
 ['St. Giuseppe Moscati: Doctor to the Poor (2007)', 123935],
 ["Women Aren't Funny (2014)", 123939],
 ['Erotikon (1929)', 123975],
 ['Spike of Bensonhurst (1988)', 123989],
 ['Maker of Men (1931)', 123995],
 ['Murder in the Fleet (1935)', 123999],
 ['I Love Lucy: The Movie (1953)', 124007],
 ['Sea Devils (1953)', 124017],
 ['The Green Hornet (1940)', 124039],
 ['Never a Dull Moment (1950)', 124095],
 ['Return of the Frontiersman (1950)', 124103],
 ['Switch (2007)', 124149],
 ['The Gallant Hours (1960)', 124182],
 ['Spring Madness (1938)', 124200],
 ['The Bugle Sounds (1942)', 124215],
 ['Song of the Open Road (1944)', 124226],
 ['Burning Down the House (2001)', 124243],
 ['Josephine And Men (1955)', 124255],
 ['The Moving Finger (1985)', 124269],
 ['Hotel Berlin (1945)', 124364],
 ['One More Tomorrow (1946)', 124366],
 ['Hard Contract (1969)', 124386],
 ['Lady by Choice (1934)', 124388],
 ["She's Working Her Way Through College (1952)", 124392],
 ['Skeleton Key 2: 667 Neighbor of the Beast (2008)', 124400],
 ['Last of the Comanches (1953)', 124408],
 ['Forty Deuce (1982)', 124422],
 ['Viva Max! (1969)', 124430],
 ['Iceberg Slim: Portrait of a Pimp (2013)', 124464],
 ['Outward Bound (1930)', 124480],
 ['The Life of Jimmy Dolan (1933)', 124486],
 ['Our Town (2007)', 124496],
 ['The Hoodlum (1919)', 124525],
 ['The Last of the Finest (1990)', 124531],
 ['Rock Around the Clock (1956)', 124548],
 ['Sånt är livet (1996)', 124629],
 ['Le joli mai (1966)', 124631],
 ['Onionhead (1958)', 124639],
 ['The Midnight Game (2013)', 124645],
 ['The Law (1990)', 124659],
 ['Sally Hemings: An American Scandal (2000)', 124667],
 ['The Day Mars Invaded Earth (1963)', 124733],
 ['The Irish in Us (1935)', 124737],
 ['Mysterious Island, The (1929)', 124765],
 ['The Lost Squadron (1932)', 124775],
 ['The Divine Lady (1929)', 124795],
 ['Men of the Fighting Lady (1954)', 124833],
 ["Jay And Silent Bob's Super Groovy Cartoon Movie (2013)", 124869],
 ['Melody for a Street Organ (2009)', 124921],
 ['Willow and Wind (2000)', 124937],
 ["House Party: Tonight's the Night (2013)", 124963],
 ['The Fine Art of Love: Mine Ha-Ha (2005)', 124975],
 ['Splendor (1989)', 125029],
 ["Sittin' on a Backyard Fence (1933)", 125079],
 ['The Feminine Touch (1941)', 125091],
 ['Voyna i mir III. - Borogyino (1967)', 125127],
 ['Safety Patrol (1998)', 125159],
 ['War and Peace (1965)', 125211],
 ['Playdate (2012)', 125233],
 ['Tenchu! (1969)', 125273],
 ['Richard Pryor: Omit the Logic (2013)', 125275],
 ['The Student Prince (1954)', 125279],
 ['Opposing Force (1986)', 125305],
 ['Margie (1946)', 125325],
 ['The Sheriff of Fractured Jaw (1959)', 125377],
 ['Trust Me (2010)', 125385],
 ["Gunslinger's Revenge (1998)", 125423],
 ['The Girl from 10th Avenue (1935)', 125427],
 ['Stage Struck (1925)', 125461],
 ['The Ghost of Yotsuya (1959)', 125467],
 ['Fun on a Weekend (1947)', 125531],
 ['Fist of Jesus (2012)', 125535],
 ['A Yank at Eton (1942)', 125551],
 ['Duffy (1968)', 125561],
 ['The Court-Martial of Jackie Robinson', 125571],
 ['The Perils of Pauline (1967)', 125574],
 ['The Fountain of Youth (1958)', 125587],
 ["Filming 'The Trial' (1981)", 125593],
 ['Port of Flowers (1943)', 125601],
 ['The Living Magoroku (1943)', 125603],
 ['Jubilation Street (1943)', 125605],
 ['Morning for the Osone Family (1946)', 125609],
 ['A Japanese Tragedy (1953)', 125611],
 ['The River Fuefuki (1960)', 125615],
 ['Immortal Love (1961)', 125617],
 ['In Our Garden', 125632],
 ['Walker (2012)', 125640],
 ['One Step Ahead of My Shadow (1933)', 125642],
 ['Lad: A Dog (1962)', 125646],
 ['Corruzione al palazzo di giustizia (1975)', 125650],
 ['Season For Assassins (1975)', 125652],
 ['Hard Luck Hero (2003)', 125700],
 ['The Missouri Traveler (1958)', 125833],
 ['The Deserter (1970)', 125840],
 ['Le Grand Jeu (1934)', 125860],
 ['Red Ensign (1934)', 125864],
 ['El asombroso mundo de Borjamari y Pocholo (2004)', 125872],
 ['FBI: Frikis buscan incordiar (2004)', 125876],
 ['Isi & Disi: Amor a lo bestia (2004)', 125878],
 ['Achtung! The Desert Tigers (1977)', 125890],
 ['Time in the Minors (2010)', 125908],
 ['Stars Above (2012)', 125910],
 ["Santa's Pocket Watch (1980)", 125928],
 ['Björk at the Royal Opera House (2002)', 125930],
 ['Christmas Comes but Once a Year (1936)', 125934],
 ['Curb Dance (2010)', 125942],
 ['Fright to the Finish (1954)', 125948],
 ["It's a Bird (1930)", 125956],
 ['Stephen Fry In America - New World', 125958],
 ['Surprise (1996)', 125980],
 ['Vengeance: The Story of Tony Cimo (1986)', 125984],
 ['Corn on the Cop (1965)', 125994],
 ['Marilyn in Manhattan (1998)', 126000],
 ['Queen - Rock Montreal (2007)', 126010],
 ['Act Da Fool (2010)', 126022],
 ['En rachâchant (1982)', 126024],
 ['The Flower (1971)', 126026],
 ['Boo to You Too! Winnie the Pooh (1996)', 126028],
 ['Halloween (1931)', 126034],
 ['The 3 Rs (2011)', 126042],
 ['Holiday for Drumsticks (1949)', 126052],
 ['Suur Tõll (1980)', 126060],
 ['We Can Be Heroes (2005)', 126062],
 ["Bob's Birthday (1994)", 126064],
 ['Summer Heights High (2007)', 126068],
 ['Haunted House (1929)', 126074],
 ['How They Get There (1997)', 126076],
 ['Istanbul (1985)', 126078],
 ['Hen, his wife (1990)', 126080],
 ['Snowballs (2011)', 126098],
 ['Beastie Boys: Sabotage (1994)', 126106],
 ['Special Delivery (2002)', 126130],
 ['Meilleur espoir féminin (2000)', 126168],
 ['Mr Reliable (1997)', 126172],
 ['Nom de code : Rose (2012)', 126176],
 ['The Sex and Violence Family Hour (1983)', 126186],
 ['Minotaur, the Wild Beast of Crete (1961)', 126194],
 ["L'isola delle svedesi (1969)", 126202],
 ['Chains (1974)', 126206],
 ['La bravata (1977)', 126221],
 ['Fährmann Maria (1936)', 126239],
 ['Thank You, Jeeves! (1936)', 126243],
 ['Homework (1989)', 126245],
 ['Double Or Nothing (1937)', 126286],
 ['Subliminal Seduction (1996)', 126331],
 ['Virtual Combat (1995)', 126333],
 ['Night Eyes Three (1993)', 126339],
 ['Love Steaks (2013)', 126560],
 ['Kocken (2005)', 126593],
 ['The Blue Knight (1973)', 126721],
 ['Bit by Bit (2002)', 126731],
 ['Bert - Den siste oskulden (1995)', 126739],
 ['En på miljonen (1995)', 126741],
 ['The Nude Princess (1976)', 126759],
 ['When Evening Falls on Bucharest or Metabolism (2013)', 126789],
 ['Two Shots Fired (2014)', 126793],
 ['Finisterrae (2010)', 126795],
 ['The Distance (2014)', 126797],
 ['Ten Minutes Older (1978)', 126917],
 ['Small Roads (2011)', 126945],
 ['Strange Voyage (1964)', 126949],
 ['Light Is Calling (2004)', 126955],
 ['The Private Life of a Cat (1944)', 126963],
 ['Letter from Siberia (1957)', 126967],
 ['Soundtracker (2010)', 126973],
 ['Kamome Diner (2006)', 126975],
 ['Dream Land (2004)', 126979],
 ['Remonstrance (1972)', 126985],
 ['The Gardener (1912)', 126989],
 ['The Girl from the Marsh Croft (1917)', 126993],
 ['Karin Daughter of Ingmar (1920)', 126995],
 ['1000 Journals (2007)', 126999],
 ['Documentarian (2013)', 127003],
 ['A Year Along the Abandoned Road', 127005],
 ['The Shoe (1998)', 127007],
 ['Min så kallade pappa (2014)', 127957],
 ['Blue Mountains, or Unbelievable Story (1984)', 127991],
 ['Private Worlds (1935)', 128015],
 ['Go, Johnny, Go! (1959)', 128027],
 ['Downtown: A Street Tale (2004)', 128047],
 ['Sartana Does Not Forgive (1968)', 128069],
 ['I Am Sartana, Trade Your Guns for a Coffin (1970)', 128077],
 ['Sartana in the Valley of Death (1970)', 128079],
 ['My Name is Texas Bill (1972)', 128115],
 ["The Castro's Abbess (1974)", 128131],
 ['Greetings from Tim Buckley (2013)', 128193],
 ['Return to Macon County (1975)', 128219],
 ['Stormy Weather (2003)', 128237],
 ['Brothers Karamazov (1969)', 128243],
 ['The Maddening (1996)', 128253],
 ['The Count of Monte Cristo (1961)', 128295],
 ['Beck - Öga för öga (1998)', 128356],
 ['Halleluja to Vera Cruz (1973)', 128373],
 ['Mark Shoots First (1975)', 128383],
 ['Highway Racer (1977)', 128393],
 ['The Iron Commissioner (1978)', 128395],
 ['Hunted City (1979)', 128401],
 ['Balkan Runner (1994)', 128421],
 ['Blood Story (1972)', 128431],
 ['Goodbye and Amen (1978)', 128433],
 ["Eurocrime! The Italian Cop and Gangster Films That Ruled the '70s (2012)",
  128480],
 ['Agent 3S3: Passport to Hell (1965)', 128492],
 ['Devil in the Brain (1972)', 128498],
 ['La tigre è ancora viva: Sandokan alla riscossa! (1977)', 128500],
 ['Lasa y Zabala (2014)', 128504],
 ['We Cause Scenes (2014)', 128514],
 ['Sacred Heart (2005)', 128516],
 ['Hits (2014)', 128544],
 ['Alla älskar Alice (2002)', 128570],
 ['Lilla Jönssonligan på styva linan (1997)', 128590],
 ['Ixcanul Volcano (2015)', 128610],
 ['As We Were Dreaming (2015)', 128616],
 ['Petting Zoo (2015)', 128624],
 ['General Spanky (1936)', 128644],
 ['Wiseguy (1996)', 128667],
 ['Casting Couch (2013)', 128673],
 ['Sputnik (2013)', 128686],
 ['Grizzly Falls (1999)', 128705],
 ['Bizarre (2015)', 128727],
 ['The Boy Soldier (1981)', 128752],
 ['La clé sur la porte (1978)', 128754],
 ['The Assassination (1972)', 128766],
 ['Tennessee Nights (1991)', 128780],
 ['This Angry Age (1957)', 128794],
 ['Monsieur Ripois (1954)', 128796],
 ['The Walls of Malapaga (1949)', 128800],
 ['Scandali nudi (1968)', 128810],
 ['Blood and Diamonds (1977)', 128816],
 ['Sesso in testa (1974)', 128818],
 ['Amarsi male (1969)', 128820],
 ['The Indifferent Beauty (1957)', 128916],
 ['Women in Cellblock 9 (1978)', 129052],
 ['Lost and Found (1979)', 129056],
 ['What Other Couples Do (2013)', 129076],
 ['Tokyo Fiancée (2015)', 129078],
 ['The Testimony (1946)', 129185],
 ['Lost Youth (1948)', 129187],
 ['The Sea That Thinks (2000)', 129189],
 ['Memphis (2013)', 129193],
 ['Jet Storm (1959)', 129211],
 ['The Argyle Secrets (1948)', 129225],
 ['Superfast! (2015)', 129250],
 ["Je m'appelle Elisabeth (2006)", 129524],
 ['Slingshot Hip Hop (2008)', 129530],
 ['Code Name Coq Rouge (1989)', 129536],
 ['The Third Reich: The Rise & Fall', 129651],
 ['A Black Ribbon for Deborah (1974)', 129661],
 ['Scandalo in Famiglia (1976)', 129663],
 ['We Always Lie to Strangers (2013)', 129667],
 ['Urban Warriors (1987)', 129677],
 ['Lady Dynamite (1973)', 129683],
 ['Who Killed the Prosecutor and Why? (1972)', 129689],
 ['My Own Man', 129705],
 ['Cose da pazzi (2005)', 129723],
 ['La vida sigue igual (1969)', 129733],
 ['Unchained (1955)', 129755],
 ['The Children of Sanchez (1978)', 129759],
 ['Violence for Kicks (1979)', 129765],
 ['Covert Action (1978)', 129769],
 ['Tamango (1958)', 129802],
 ['Capturing Mary (2007)', 129838],
 ['Somewhere Under the Broad Sky (1954)', 129847],
 ['Old Man Drinking a Glass of Beer (1898)', 129849],
 ['Dickson Greeting (1891)', 129851],
 ['Hallucination Strip (1975)', 129865],
 ['Snapshot of a Crime (1975)', 129869],
 ['My Wife, A Body to Love (1973)', 129871],
 ['Pigs with a P.38 (1978)', 129875],
 ["Clap, You're Dead (1974)", 129877],
 ['Orders Signed in White (1974)', 129879],
 ['Il cappotto di legno (1981)', 129881],
 ['Le ultime ore di una vergine (1972)', 129885],
 ['Moving Alan', 129887],
 ['Sex of the Witch (1973)', 129895],
 ['Butterflies Have No Memories (2009)', 129915],
 ['The Dependent (1969)', 129917],
 ['Nazareno Cruz and the Wolf (1975)', 129919],
 ['El Escarabajo de Oro (2014)', 129925],
 ['Autohystoria (2007)', 129929],
 ['La Morte Rouge (2006)', 129931],
 ['Asthma (2014)', 129943],
 ['Password: Uccidete agente Gordon (1966)', 129980],
 ['The incredible Paris Incident (1967)', 129986],
 ['One Man Against the Organization (1975)', 129996],
 ['Des fleurs pour Algernon (2006)', 130060],
 ['Crazy Beautiful You (2015)', 130089],
 ['A Girl, A Guy, And A Gob (1941)', 130093],
 ['Babe Ruth (1998)', 130099],
 ['Les grandes chaleurs (2009)', 130144],
 ['Hooray for Love (1935)', 130165],
 ['Juggernaut (1936)', 130178],
 ['Patty Hearst (1988)', 130204],
 ['Standoff (1998)', 130231],
 ['With or Without You (1999)', 130235],
 ['Wild Thing (1987)', 130237],
 ['Warriors Five (1962)', 130239],
 ['The Case of the Velvet Claws (1936)', 130252],
 ['The Discoverers (2014)', 130259],
 ['Thunder Alley (1967)', 130280],
 ['A Fight For (2014)', 130296],
 ['Pot v raj (2014)', 130298],
 ['The Strength of Water (2009)', 130324],
 ['Ice Poison (2014)', 130342],
 ['Men in White (1998)', 130386],
 ["Foolin' Around (1980)", 130410],
 ["Three into Two Won't Go (1969)", 130430],
 ['Akenfield (1974)', 130432],
 ['The Coconut Revolution (2000)', 130446],
 ['Michael Laudrup - en Fodboldspiller', 130454],
 ['Among the Living (1941)', 130456],
 ['Baby Snakes (1979)', 130472],
 ['Laissons Lucie faire ! (2000)', 130500],
 ['Venus & Fleur (2004)', 130502],
 ['I giorni contati (1963)', 130532],
 ['Get Christie Love! (1974)', 130552],
 ['Shark Kill (1976)', 130558],
 ['Daddy, Darling (1970)', 130620],
 ['The Thunder Kick (1974)', 130652],
 ['Little Girl, Big Tease (1976)', 130666],
 ["Slumber Party '57 (1976)", 130672],
 ['Cheerleaders Beach Party (1978)', 130690],
 ['Lunar Cop (1995)', 130716],
 ['Shablul (1971)', 130732],
 ['Love Lies Bleeding (1999)', 130770],
 ['Deadly Illusion (1987)', 130776],
 ['Wild 90 (1968)', 130810],
 ['Maidstone (1970)', 130812],
 ['Midnight Ride (1990)', 130814],
 ['Street Knight (1993)', 130820],
 ['Dancers (1987)', 130834],
 ['Julie Darling (1983)', 130844],
 ['The Birthday Party (1968)', 130846],
 ['Brothers on the Line (2012)', 130852],
 ['Monaco Forever (1984)', 130860],
 ['Gorilla Bathes at Noon (1993)', 130866],
 ['Children of Rage (1975)', 130876],
 ['Doppelgänger Paul (2012)', 130878],
 ["McCinsey's Island (1998)", 130882],
 ['Gospel According to Harry (1994)', 130918],
 ['Tiffany Jones (1973)', 130932],
 ['The Four Dimensions of Greta (1972)', 130936],
 ['School for Sex (1969)', 130946],
 ['Musikanten (2006)', 130962],
 ['Champions (1984)', 130968],
 ['Filmistaan (2014)', 131021],
 ['Mara und der Feuerbringer (2015)', 131029],
 ['La liga no es cosa de hombres (1972)', 131031],
 ['Benjamin Blümchen - Seine schönsten Abenteuer (2006)', 131078],
 ['The Fearless Four (1997)', 131108],
 ['Closed Curtain (2013)', 131172],
 ['A Dream of Kings (1969)', 131186],
 ['Blueberry Hill', 131198],
 ['Compound Fracture (2013)', 131209],
 ['Plague (1979)', 131223],
 ['Pleasure Palace', 131225],
 ['Rentun Ruusu (2001)', 131260],
 ['Hotline (1982)', 131276],
 ['Terror on the 40th Floor', 131280],
 ['The Odd Angry Shot (1979)', 131294],
 ['Breaking Point - Pornografisk Thriller (1975)', 131300],
 ['Fort Yuma (1955)', 131320],
 ['Somebody Killed Her Husband (1978)', 131361],
 ['A Covenant with Death (1967)', 131371],
 ['Safe at Home! (1962)', 131391],
 ['The Honkers (1972)', 131415],
 ['The young Rajah (1922)', 131427],

In [76]:
no_genres_movie_df = pd.DataFrame(no_genre_movies, columns = ['title', 'movieId'])
no_genres_movie_df.head()

                                             title  movieId
0            Away with Words (San tiao ren) (1999)    83773
1                            Scorpio Rising (1964)    83829
2                                Glitterbug (1994)    84768
3  Age of the Earth, The (A Idade da Terra) (1980)    86493
4                          Trails (Veredas) (1978)    87061

In [81]:
no_genres_movie_df.head(30)

                                                title  movieId
0               Away with Words (San tiao ren) (1999)    83773
1                               Scorpio Rising (1964)    83829
2                                   Glitterbug (1994)    84768
3     Age of the Earth, The (A Idade da Terra) (1980)    86493
4                             Trails (Veredas) (1978)    87061
5                            Milky Way (Tejút) (2007)    91246
6        Dancing Hawk, The (Tanczacy jastrzab) (1978)    92435
7             Warsaw Bridge (Pont de Varsòvia) (1990)    92641
8                       Ella Lola, a la Trilby (1898)    94431
9                     Turkish Dance, Ella Lola (1898)    94657
10                            Blacksmith Scene (1893)    95541
11      Promise of the Flesh (Yukcheui yaksok) (1975)    95750
12                                 Nocturno 29 (1968)    96479
13                        Les hautes solitudes (1974)    96651
14                        Direct from Brooklyn (1999)   113472
15         Primus Hallucino-Genetics Live 2004 (2004)   113545
16                                  La cravate (1957)   114335
17            Glumov's Diary (Dnevnik Glumova) (1923)   114587
18                                     At Land (1944)   114723
19         Study in Choreography for Camera, A (1945)   114725
20                                    Guernica (1950)   114877
21             It's My Mother's Birthday Today (2008)   115004
22                              Spare Bed-Room (1969)   115006
23                              Maria (Mariya) (1989)   115419
24  (Absolutions) Pipilotti's Mistakes ((Entlastun...   115441
25                               Judgement Day (1983)   115529
26  Two Solutions for One Problem (Dow Rahehal Bar...   115602
27                               Madame Bovary (2000)   115893
28                           Christmas Oranges (2012)   116046
29                              Clockwork Mice (1995)   116054

In [50]:
nan_movies=pd.read_csv("Data/nan_movies.csv")
nan_movies.shape

(326, 3)

In [37]:
nan_movies.head(10)

   Unnamed: 0  movieId                                  title
0           0    32930         Category 6: Day of Destruction
1           1    40697                              Babylon 5
2           2    79607                      The Millions Game
3           3    87442                  Bicycle, Spoon, Apple
4           4   112406  Brazil: In the Shadow of the Stadiums
5           5   113190                     Slaying the Badger
6           6   115133             Tatort: Im Schmerz geboren
7           7   123619                     Terrible Joe Moran
8           8   125571   The Court-Martial of Jackie Robinson
9           9   125632                          In Our Garden

'\nimport imdb\n# creating instance of IMDb\nia = imdb.IMDb()\nmovies_year=[]\nstart=0\nend=3\n'

'\nfor x in nan_movies["title"]:\n    # getting the movie with name\n    search = ia.search_movie(x)\n    #count+=1\n    # getting movie year\n    if len(search)==0:\n        movies_year.append("")\n        continue\n    year = str(search[0][\'year\'])\n    print(x + " : " + year)\n    movies_year.append(year)\n# printing movie name and year\n#print(search[0][\'title\'] + " : " + str(year))\n'

In [45]:
#movies_year

'\nimport imdb\n   \n# creating instance of IMDb\nia = imdb.IMDb()\n\n# getting the movie with name\nsearch = ia.search_movie("Tatort: Im Schmerz geboren")\nprint(search[0][\'genres\'])\n#for genre in search[\'genres\']:\n#    print(genre)\n# getting movie year\nsearch[0][\'year\']\n#search\n\n'

In [18]:
#pip install cinemagoer

In [86]:
print(links[links['movieId']==83829]['imdbId'].values[0])
links[links['movieId']==83829]

58555

       movieId  imdbId   tmdbId
16677    83829   58555  46787.0

In [57]:
## Get movie year from IMDB
count=0
# create an instance of the Cinemagoer class
ia = Cinemagoer()

for x,m in zip(nan_movies['movieId'],nan_movies['title']):
    y = links[links['movieId']==x]['imdbId'].values[0]
     ##############
        ######## DO NOT TOUCH THIS CODE #####################
    # get a movie
    movie = ia.get_movie(y)
    
    if (count%100==0):
        print(count,"------- Done ----------")
        print(m,movie['year'])
    count+=1
    
    ################## DO Not Touch this code --------########

0 ------- Done ----------
Category 6: Day of Destruction 2004
100 ------- Done ----------
Veljet 1991
200 ------- Done ----------
Maria Bamford: Old Baby 2017
300 ------- Done ----------
Veras Mantel 2017

In [66]:
no_genre_movies[0][1]
len(no_genre_movies)
print(no_genre_movies[0][1],no_genre_movies[0][0])

83773 Away with Words (San tiao ren) (1999)

In [87]:
# get genres of 
# create an instance of the Cinemagoer class
ia = Cinemagoer()

# get a movie
movie = ia.get_movie('58555')

# print the genres of the movie
print('Genres:')
print(movie['genres'])

Genres:
['Short', 'Music']

# Ratings csv

In [10]:
ratings= pd.read_csv("Data/ratings.csv")
ratings.head()

   userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264

In [72]:
print(ratings.shape)
print(len(ratings["userId"].unique()))
print(len(ratings["movieId"].unique()))
print(len(ratings["rating"].unique()))
## So we have movieId unique

(27753444, 4)
283228
53889
10

In [6]:
## timestamp has nothing to do in any queries
## there are total 283228 user id
## Not all the movies have been rated 53889

# Tags csv

In [11]:
tags= pd.read_csv("Data/tags.csv")
tags.head()

   userId  movieId           tag   timestamp
0      14      110          epic  1443148538
1      14      110      Medieval  1443148532
2      14      260        sci-fi  1442169410
3      14      260  space action  1442169421
4      14      318  imdb top 250  1442615195

In [89]:
## timestamp needs to be removed
## perform lowercase uppercase operation 
## NEW TABLE FOR TAGS

In [75]:
print(tags.shape)
print(len(tags["userId"].unique()))
print(len(tags["movieId"].unique()))
print(len(tags["tag"].unique()))

(1108997, 4)
19325
45981
74715